# Generated by Django 4.1.7 on 2023-03-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_alter_message_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
